import { Metadata } from "next";
import LandingPage from "./template";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <LandingPage />
    </div>
  );
}
