import React from "react";
import ProductDetail from "../template";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Product Detail Page",
  description: "Generated by create next app",
};
const page = () => {
  return <ProductDetail />;
};

export default page;
